CREATE TABLE IF NOT EXISTS order_detail (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_number VARCHAR(12) NOT NULL,
	email VARCHAR(250) NOT NULL,
	promo_code VARCHAR(8),
	quantity INT(4) NOT NULL
)
